### ISSUE TITLE
About - Typo

### ISSUE THREAD

**Issue by asacxyz** [Flutterando/asp#1]
Boa noite,

Abrindo este issue para avisar que na seção **About**, está escrito "Pattenr" ao invés de "Pattern"
![image](https://github.com/Flutterando/asp/assets/60830711/7bedcf86-b0a3-48f5-bb3a-67951469c502)

Espero ter ajudado,
André

**Comment by dtodt** [comment]
I think that this issue is solved, and could be closed.
