### ISSUE TITLE
Change collections, RxList, RxMap

### ISSUE THREAD

**Issue by lucas3g** [Flutterando/asp#6]
Change collections, RxList, RxMap and others that exist for AtomList, AtomMap...

**Comment by isaquepinheiro** [comment]
> Change collections, RxList, RxMap and others that exist for AtomList, AtomMap...

Not testing and looking at the Readme, I found the new declaration as follows: 

RxList for: "\<Product\>[].asAtom();"

in https://github.com/Flutterando/asp#atoms

But in my humble opinion, I would remove all the "Rx" names from the package and adopt the new name "asp" or "atom".
